### ISSUE TITLE
Model bin file is missing 

### ISSUE THREAD

**Issue by 12345k** [12345k/IIR#5]
@varshni98   Can you please take a look  on it
```

➜  IIR git:(main) ✗ sudo docker run -it -p 6001:6001 iir    
Traceback (most recent call last):
  File "/app/main.py", line 27, in <module>
    STATE_DICT = torch.load("NER/Resume Model/model-state.bin_1", map_location=DEVICE)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'NER/Resume Model/model-state.bin_1'
➜  IIR git:(main) ✗ A
```

**Comment by VpkPrasanna** [comment]
Model file can be found here
Have a look @12345k
https://drive.google.com/drive/folders/1od3-B0Gy7iRRcqTdOyDqyGdkYLKmgQ_1?usp=sharing

**Comment by VpkPrasanna** [comment]
@varshni98  update the model path in readme file .

**Comment by VpkPrasanna** [comment]
Closing this issue as the model file path is added in README
